// Types are derived from Zod schemas in ../schemas/index.ts.
// Do not edit this file manually — update the schemas instead.
export type {
  DisplayConfig,
  PaneConfig,
  LayoutChild,
  LayoutNode,
  SessionInfo,
  WSControlMessage,
  SSHConnectionsResponse,
} from '../schemas'
