export const TERMINAL_FONT_FAMILY = [
  '"Terminal Powerline"',
  '"Meslo LG M for Powerline"',
  '"Meslo LG M DZ for Powerline"',
  '"Source Code Pro for Powerline"',
  '"Symbol Neu for Powerline"',
  '"Cascadia Code"',
  '"Fira Code"',
  '"JetBrains Mono"',
  '"SF Mono"',
  'Monaco',
  'Menlo',
  '"Osaka-Mono"',
  '"MS Gothic"',
  '"Noto Sans Mono CJK JP"',
  '"Noto Sans Mono CJK SC"',
  '"Noto Sans Mono CJK TC"',
  '"Noto Sans Mono"',
  '"Noto Sans JP"',
  '"PingFang SC"',
  '"PingFang TC"',
  '"Hiragino Sans"',
  '"Yu Gothic UI"',
  'monospace',
].join(', ')
